config/routes.rb
Rails.application.routes.draw do
  devise_for :authors

  #devise_for :authors do get '/authors/sign_out' => 'devise/sessions#destroy' 
  #  get 'authors/:id' => 'users#show'
  #end

  get "authors/books/:id/edit" => "books#edit"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  resources :books do
    resources :reviews
  end
 # resources :reviews
  resources :users
  resources :authors
  resources :books
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root "authors#index"
  
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :confirmable, :lockable, :timeoutable#, :omniauthable, omniauth_providers: [:twitter]
  
  has_many :books
  #has_many :reviews
  #has_secure_password
  validates :name,
      presence: true,
      length: {minimum: 3,maximum: 10}

  validates :gender,
      presence: true,
      inclusion:{ in: ['male','female']}
  #male->0,female->1
  validates :encrypted_password,
      presence: true,
      length: {minimum: 6}
  validates :email,
      presence: true,
      uniqueness: {case_sensitive:false}
  validates :email, confirmation: true
  validates :agreement, acceptance: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_author!, only: [:show, :update, :edit, :destroy, :create]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    @books = Book.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @books=Book.where(author_id: params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @books=Book.where(author_id: @author.id).destroy_all
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:gender, :name, :password, :age, :email, :email_confiration, :agreement)
    end



end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= form_for(author) do |f|
  - if author.errors.any?
    #error_explanation
      %h2
        = pluralize(author.errors.count, "error")
        prohibited this author from being saved:
      %ul
        - author.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :age
    = f.text_field :age
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :email_confirmation
    %br/
    = f.text_field :email_confirmation
  .field
    = f.label :agreement
    %br/
    = f.check_box :agreement
  .actions
    = f.submit

app/views/authors/edit.html.haml
%h1 Editing Author
= render 'form', author: @author
= link_to 'Show', @author
|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%section.hero.is-info.is-medium.is-bold
  .hero-body
    .container.has-text-centered
      %p#notice
        = notice
      %p.alert= alert
      - if author_signed_in?
        %h1.title
          こんにちは#{current_author.name}さん
        %br/
        %h2.subtitle
          = link_to("本を登録する。","/books/new", class: "button is-white")
          = link_to("本を編集する。","/authors/#{current_author.id}",class: "button is-white")
      - else
        %h1.title ログインして下さい。
.hero-body
  .container.has-text-centered
    .columns.is-vcentered
      .column.is-4
        %h2.fa-2x 著者一覧
        %table.table.is-fullwidth
          %thead
            %tr
              %th Gender
              %th Name
              %th Age
              %th{:colspan => "3"}
          %tbody
            - @authors.each do |author|
              %tr
                %td= author.gender
                %td= author.name
                %td= author.age
                %td= link_to('Show', author, class: "button is-small is-black is-inverted")
      .column.is-6.is-offset-1
        %h2.fa-2x 書籍一覧
        %table.table.is-fullwidth
          %thead
            %tr
              %th Title
              %th Published at
              %th Price
              %th{:colspan => "3"}
          %tbody
            - @books.each do |book|
              %tr
                %td= book.title
                %td= book.published_at
                %td= book.price
                %td= link_to('Show',book, class: "button is-small is-black is-inverted")

app/views/authors/new.html.haml
%h1 New Author
= render 'form', author: @author
= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice
%section.section
  .container
    .columns
      .column.is-3
        %aside.is-medium.menu
          %p.menu-label
            Details
          %ul.menu-list.fa-1x
            %li
              %strong Gender:
              = @author.gender
            %br/
            %li
              %strong Age:
              = @author.age
            %br/
            %li
              %strong Name:
              = @author.name
            %br/
            %li
              = link_to 'Back', authors_path
      .column.is-8
        %aside.content.is-medium
          %h2.title
            「#{@author.name}」さんの著書
          %hr/
          %ul.menu-list.fa-1x
            - @books.each do |book|
              .box
                %li
                  %span= link_to( book.title, "/books/#{book.id}/edit")