vender/bundle/gems/letter_opener_web-1.3.4/config/routes.rb
# frozen_string_literal: true

LetterOpenerWeb::Engine.routes.draw do
  delete 'clear'                 => 'letters#clear',    :as => :clear_letters
  delete ':id'                   => 'letters#destroy',  :as => :delete_letter
  get    '/'                     => 'letters#index',    :as => :letters
  get    ':id(/:style)'          => 'letters#show',     :as => :letter
  get    ':id/attachments/:file' => 'letters#attachment'
end

vender/bundle/gems/letter_opener_web-1.3.4/app/models/letter_opener_web/letter.rb
# frozen_string_literal: true

module LetterOpenerWeb
  class Letter
    attr_reader :id, :sent_at

    def self.letters_location
      @letters_location ||= LetterOpenerWeb.config.letters_location
    end

    def self.letters_location=(directory)
      LetterOpenerWeb.configure { |config| config.letters_location = directory }
      @letters_location = nil
    end

    def self.search
      letters = Dir.glob("#{LetterOpenerWeb.config.letters_location}/*").map do |folder|
        new(id: File.basename(folder), sent_at: File.mtime(folder))
      end
      letters.sort_by(&:sent_at).reverse
    end

    def self.find(id)
      new(id: id)
    end

    def self.destroy_all
      FileUtils.rm_rf(LetterOpenerWeb.config.letters_location)
    end

    def initialize(params)
      @id      = params.fetch(:id)
      @sent_at = params[:sent_at]
    end

    def plain_text
      @plain_text ||= adjust_link_targets(read_file(:plain))
    end

    def rich_text
      @rich_text ||= adjust_link_targets(read_file(:rich))
    end

    def to_param
      id
    end

    def default_style
      style_exists?('rich') ? 'rich' : 'plain'
    end

    def attachments
      @attachments ||= Dir["#{base_dir}/attachments/*"].each_with_object({}) do |file, hash|
        hash[File.basename(file)] = File.expand_path(file)
      end
    end

    def delete
      FileUtils.rm_rf("#{LetterOpenerWeb.config.letters_location}/#{id}")
    end

    def exists?
      File.exist?(base_dir)
    end

    private

    def base_dir
      "#{LetterOpenerWeb.config.letters_location}/#{id}"
    end

    def read_file(style)
      File.read("#{base_dir}/#{style}.html")
    end

    def style_exists?(style)
      File.exist?("#{base_dir}/#{style}.html")
    end

    def adjust_link_targets(contents)
      # We cannot feed the whole file to an XML parser as some mails are
      # "complete" (as in they have the whole <html> structure) and letter_opener
      # prepends some information about the mail being sent, making REXML
      # complain about it
      contents.scan(%r{<a\s[^>]+>(?:.|\s)*?</a>}).each do |link|
        fixed_link = fix_link_html(link)
        xml        = REXML::Document.new(fixed_link).root
        next if xml.attributes['href'] =~ /(plain|rich).html/
        xml.attributes['target'] = '_blank'
        xml.add_text('') unless xml.text
        contents.gsub!(link, xml.to_s)
      end
      contents
    end

    def fix_link_html(link_html)
      # REFACTOR: we need a better way of fixing the link inner html
      link_html.dup.tap do |fixed_link|
        fixed_link.gsub!('<br>', '<br/>')
        fixed_link.scan(/<img(?:[^>]+?)>/).each do |img|
          fixed_img = img.dup
          fixed_img.gsub!(/>$/, '/>') unless img =~ %r{/>$}
          fixed_link.gsub!(img, fixed_img)
        end
      end
    end
  end
end

vender/bundle/gems/letter_opener_web-1.3.4/app/controllers/letter_opener_web/application_controller.rb
# frozen_string_literal: true

module LetterOpenerWeb
  class ApplicationController < ActionController::Base
  end
end

vender/bundle/gems/letter_opener_web-1.3.4/app/controllers/letter_opener_web/letters_controller.rb
# frozen_string_literal: true

require_dependency 'letter_opener_web/application_controller'

module LetterOpenerWeb
  class LettersController < ApplicationController
    before_action :check_style, only: [:show]
    before_action :load_letter, only: %i[show attachment destroy]

    def index
      @letters = Letter.search
    end

    def show
      text = @letter.send("#{params[:style]}_text")
                    .gsub(/"plain\.html"/, "\"#{routes.letter_path(id: @letter.id, style: 'plain')}\"")
                    .gsub(/"rich\.html"/, "\"#{routes.letter_path(id: @letter.id, style: 'rich')}\"")

      render html: text.html_safe
    end

    def attachment
      filename = "#{params[:file]}.#{params[:format]}"
      file     = @letter.attachments[filename]

      return render plain: 'Attachment not found!', status: 404 unless file.present?
      send_file(file, filename: filename, disposition: 'inline')
    end

    def clear
      Letter.destroy_all
      redirect_to routes.letters_path
    end

    def destroy
      @letter.delete
      redirect_to routes.letters_path
    end

    private

    def check_style
      params[:style] = 'rich' unless %w[plain rich].include?(params[:style])
    end

    def load_letter
      @letter = Letter.find(params[:id])
      head :not_found unless @letter.exists?
    end

    def routes
      LetterOpenerWeb.railtie_routes_url_helpers
    end
  end
end

vender/bundle/gems/letter_opener_web-1.3.4/app/views/layouts/letter_opener_web/letters.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LetterOpenerWeb</title>
  <%= stylesheet_link_tag    "letter_opener_web/application", :media => "all" %>
  <%= javascript_include_tag "letter_opener_web/application" %>
  <%= favicon_link_tag       "letter_opener_web/blue-dot.ico", :rel => "icon" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

vender/bundle/gems/letter_opener_web-1.3.4/app/views/letter_opener_web/letters/index.html.erb
<div class="col left">
  <h1>
    Letters
    <span class="pull-right">
      <%= link_to letters_path, class: 'btn refresh' do %>
        <i class="icon-refresh"></i>
        Refresh
      <% end %>
      <%= link_to clear_letters_path, method: 'delete', data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
        <i class="icon-trash icon-white"></i>
        Clear
      <% end %>
    </span>
  </h1>
  <table class="table table-hover letter-opener" data-letters-path="<%= letters_path %>">
    <thead>
      <tr>
        <th>ID</th>
        <th>Sent at</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% if first_letter = @letters.shift %>
        <tr class="active">
          <td>
            <%= link_to(first_letter.id, letter_path(first_letter, style: first_letter.default_style), target: 'mail') %>
          </td>
          <td><%= first_letter.sent_at %></td>
          <td>
            <%= link_to delete_letter_path(first_letter), method: 'delete', data: { confirm: 'Are you sure you want to delete this email?' } do %>
              <span class="pull-right">
                <i class="icon-remove-circle" title="Delete"></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% @letters.each do |letter| %>
        <tr>
          <td>
            <%= link_to(letter.id, letter_path(letter, style: letter.default_style), target: 'mail') %>
          </td>
          <td><%= letter.sent_at %></td>
          <td>
            <%= link_to delete_letter_path(letter), :method => 'delete', data: { confirm: 'Are you sure you want to delete this email?' } do %>
              <span class="pull-right">
                <i class="icon-remove-circle"></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col right">
  <iframe name="mail" id="mail" src="<%= first_letter.present? ? letter_path(first_letter, style: first_letter.default_style) : 'about:blank' %>"></iframe>
</div>