config/routes.rb
Rails.application.routes.draw do
  devise_for :authors

  #devise_for :authors do get '/authors/sign_out' => 'devise/sessions#destroy' 
  #  get 'authors/:id' => 'users#show'
  #end

  get "authors/books/:id/edit" => "books#edit"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  resources :books do
    resources :reviews
  end
 # resources :reviews
  resources :users
  resources :authors
  resources :books
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root "authors#index"
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title BookApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.6.3/css/all.css", :integrity => "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/", :rel => "stylesheet"}/
    %link{:href => "../images/favicon.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700", :rel => "stylesheet"}/
    / Bulma Version 0.7.2
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css", :rel => "stylesheet"}/
    %link{:href => "../css/inbox.css", :rel => "stylesheet", :type => "text/css"}/
    :css
      body{
        background-color:  #eeeeee;
        width: auto;
      }
  %body
    %nav.navbar.has-shadow
      .container
        .navbar-brand
          -#= link_to(image_tag('Title.png'),"/",class: "navbar-item")
          = link_to("BookApp","/",class: "navbar-item fa-2x")
          .navbar-burger.burger
            #nav-drawer
              %input#nav-input.nav-unshown{:type => "checkbox"}/
              %label#nav-open{:for => "nav-input"}
                %span
              %label#nav-close.nav-unshown{:for => "nav-input"}
              #nav-content 
                %br
                - if author_signed_in?
                  = link_to("変更",edit_author_registration_path, class: "navbar-item fas fa-users-cog")
                  = link_to("",destroy_author_session_path, method: :delete, class: "navbar-item fas fa-sign-out-alt")
                - else
                  = link_to("サインアップ",new_author_registration_path, class: "navbar-item fas fa-user-plus")
                  = link_to("ログイン",new_author_session_path, class: "navbar-item fas fa-sign-in-alt")
      #navMenu.navbar-menu
        .navbar-end
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link
              Account
              .navbar-dropdown
                - if author_signed_in?
                  = link_to("プロフィール変更",edit_author_registration_path, class: "navbar-item")
                  = link_to("ログアウト",destroy_author_session_path, method: :delete, class: "navbar-item")
                - else
                  = link_to("サインアップ",new_author_registration_path, class: "navbar-item")
                  = link_to("ログイン",new_author_session_path, class: "navbar-item")




    -# %nav.navbar.has-shadow
    -#   .container
    -#     .navbar-brand
    -#       = link_to(image_tag('/Title.png'),"/",class: "navbar-item")
    -#       .navbar-burger.burger{"data-target" => "navMenu"}
    -#         %span
    -#         %span
    -#         %span
    -#     #navMenu.navbar-menu
    -#       .navbar-end
    -#         .navbar-item.has-dropdown.is-active
    -#           %a.navbar-link
    -#             Account
    -#           .navbar-dropdown
    -#             %a.navbar-item
    -#               Dashboard
    -#             %a.navbar-item
    -#               Profile
    -#             %a.navbar-item
    -#               Settings
    -#             %hr.navbar-divider/
    -#             .navbar-item
    -#               Logout


    -# %nav.navbar.has-shadows
    -#   .container
    -#     .navbar-brand.fa-2x
    -#       .nav-item
    -#         %span.icon
    -#           %i.fas.fa-book-reader
    -#           = link_to(image_tag('/Title.png'),"/",class: "navbar-item")
    -#       .navbar-burger.burger.fa-0.5x{"data-target" => "navMenu"}
    -#         - if author_signed_in?
    -#           = link_to("変更",edit_author_registration_path, class: "navbar-item fas fa-users-cog")
    -#           = link_to("",destroy_author_session_path, method: :delete, class: "navbar-item fas fa-sign-out-alt")
    -#         - else
    -#           = link_to("サインアップ",new_author_registration_path, class: "navbar-item fas fa-user-plus")
    -#           = link_to("ログイン",new_author_session_path, class: "navbar-item fas fa-sign-in-alt")
    -#     #navMenu.navbar-menu
    -#       .navbar-end
    -#         .navbar-item.has-dropdown.is-hoverable
    -#           %a.navbar-link
    -#             Account
    -#           .navbar-dropdown
    -#             - if author_signed_in?
    -#               = link_to("プロフィール変更",edit_author_registration_path, class: "navbar-item")
    -#               = link_to("ログアウト",destroy_author_session_path, method: :delete, class: "navbar-item")
    -#             - else
    -#               = link_to("サインアップ",new_author_registration_path, class: "navbar-item")
    -#               = link_to("ログイン",new_author_session_path, class: "navbar-item")
    = yield


    %footer.footer
      .container
        .content.has-text-centered
          %p
            ©️2018 ShunInadumi